### ISSUE TITLE
SDK v3.x: `enum PinwheelEventType` still contains `case inputAmount`

### ISSUE THREAD

**Issue by jpeckner** [underdog-tech/pinwheel-ios-sdk#113]
# 🐛 Bug Report

## Describe the bug

This isn't strictly a bug, but it's leading to warnings in my app: in SDK v3.x, `enum PinwheelEventType` still contains `case inputAmount`, even though the `input_amount` [event was removed](https://docs.pinwheelapi.com/public/changelog/new-major-sdk-versions).

### To Reproduce

1. Install SDK v3.0.4.
2. Inspect `enum PinwheelEventType`.

### Expected behavior

`case inputAmount` should be deleted if it's never sent to `PinwheelDelegate` instances.

### Screenshots
`enum PinwheelEventType` as seen in v3.0.4:

<img width="950" alt="Screenshot 2024-04-04 at 11 48 45 AM" src="https://github.com/underdog-tech/pinwheel-ios-sdk/assets/19365492/400e3d9a-7860-4aec-ae95-99af1c35d490">

### Environment (please complete the following information)

- Version: 3.0.4
- Xcode: 15.1
- Swift version: 5.9

**Comment by roscioli** [comment]
Thank you @jpeckner for the flag! This should be fixed now in 3.0.5

**Comment by jpeckner** [comment]
@roscioli Thanks! Sorry for the delay getting back to you, but thanks for removing `case inputAmount`.

Is there any documentation about the new `PinwheelOtherEventPayload` that was added in this version? I didn't see anything about it [here](https://docs.pinwheelapi.com/public/docs/link-events); appreciate if you could point me to the right docs, or detail the circumstances under which `PinwheelOtherEventPayload` can be returned.
